dna = input("Введите последовательность ДНК:ATGCGTAACGTA ").upper()

count_A = dna.count("A")
count_T = dna.count("T")
count_G = dna.count("G")
count_C = dna.count("C")
print("-" * 25)
print("Подсчёт нуклеотидов:")

print(f"A: {count_A}")
print(f"T: {count_T}")
print(f"G: {count_G}")
print(f"C: {count_C}")
print("-" * 25)
character_count = len(dna)
print(f"Общая длина: {character_count}")

result_A = (count_A / character_count)
result_T = (count_T / character_count)
result_G = (count_G / character_count)
result_C = (count_C / character_count)
print("-" * 25)
print("Процентное соотношение:")
print(f"А: {result_A:.2%}")
print(f"T: {result_T:.2%}")
print(f"G: {result_G:.2%}")
print(f"C: {result_C:.2%}")